title: "Evgeny Shulyak"
author: "Evgeny Shulyak"
description: "Evgeny Shulyak"
permalink: /:title/
lang: "ru"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false            # show article excerpts instead of archive list on the home page
show_frame: false              # display a grey frame on large screens
show_sidebar: true            # show a sidebar instead of the usual header
show_minimal: false             # remove all clutter

#show_frame: "/assets/images/background.svg"

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:                     # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {file: "Home.md"}
  # - {file: "linux.html"}
  # - {file: "README.md"}
  
  
external:                       # accepts {file, title, url, icon, sidebaricon}
  - {title: VK, url: "https://vk.com/jenit777"}
  - {title: "Мои заметки", url: "https://vk.com/club215896332"}
  - {title: Github, url: "https://github.com/evgeny735/"}
  - {file: "archive.html"}
  # - {title: Mail, icon: envelope, url: "mailto:author@example.com"}
  # - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

plugins:
 - jekyll-feed
 - jekyll-paginate
 - jekyll-redirect-from
 - jekyll-sitemap

exclude: [vendor] 

paginate: 5

